//
// Created by milesosborne on 12/3/22.
//

#ifndef CEC_470_PROJECT_2_MEMORY_INSTRUCTION_LIB_H
#define CEC_470_PROJECT_2_MEMORY_INSTRUCTION_LIB_H

/* Memory Instruction Macros */
#define MEM_METHOD_BIT_POSITION 1
#define MEM_REGISTER_BIT_POSITION 2
#define MEM_FUNCTION_BIT_POSITION 3

#define MEM_METHOD_BIT_MASK (0X3 << MEM_METHOD_BIT_POSITION)
#define MEM_REGISTER_BIT_MASK (1 << MEM_REGISTER_BIT_POSITION)
#define MEM_FUNCTION_BIT_MASK (1 << MEM_FUNCTION_BIT_POSITION)

#define LOAD_OP     1
#define STORE_OP    0

#define REG_ACC     0
#define REG_IR_MAR  1

#endif //CEC_470_PROJECT_2_MEMORY_INSTRUCTION_LIB_H
